// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvwoviyzizfqqdezguwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2d292aXl6aXpmcXFkZXpndXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTM2MDIsImV4cCI6MjA3MDE2OTYwMn0.UWtL6adOYcS9UtZcLrAUQv7taJwlRjcs43Ir5lqHKQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});